### ISSUE TITLE
Bug: orientation change resets everything

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [daothanhduy305/KRichEditor#11]
Steps:
1. write something.
2. change orientation.

The bug:
All that you've written is gone.

Suggestion for fixing it:
implement onSaveInstanceState, put there the content of it, and restore on onCreate.

**Comment by daothanhduy305** [comment]
Oh right, I forgot ab this. Thanks for pointing it out.

**Comment by daothanhduy305** [comment]
And feel free to pull request for bugs fixing as well as source enhancing (re-implement things or so) if you like :relaxed: I'm very open to any better idea :wink:

**Comment by AndroidDeveloperLB** [comment]
Sadly I'm tight on schedule.
If I had the time, I would actually make my own solution from scratch, without using WebView.

**Comment by AndroidDeveloperLB** [comment]
Looking at what you've changed, I see all you did is to enable retainInstance  in the fragment.
This is not a good solution.
It's not available for Activity. Only for Fragment, and it's not the official way to save the state of a view. 
You are supposed to use onSaveInstanceState  instead, and restore it on onRestoreInstanceState.
Just like any other view.
Example here:
https://stackoverflow.com/a/3542895/878126
Since this library is about the text editor, it should consist of a functional View, as replacement to EditText. Not a fragment.

**Comment by AndroidDeveloperLB** [comment]
Another reason:
I don't think retainInstance actually saves the state on all cases. Only orientation change.
Try other triggers, and you will see. For example locale change.

**Comment by daothanhduy305** [comment]
I'm also aware of the instabilities cause by "other changes". For time being, I would make this as enabling retainInstance (I'm also aware that this is not the ultimate approach). In this case, it's not that easy to correctly implement the onSavedInstance and onCreate (load the saved bundle):
- I'm using anko view to create view and the onCreateView() as you know, would be triggered multiple times on activity restart (due to configuration changes). So it would cost a little too much to spam the setContent(savedData) method of internal editor on restoring through onCreateView. If you look back 1 more commit, you'll  see I had thought of the proper implementation before deciding to go with retainInstance.
- The thing is I'm using (the ugly) webview, everything would be asynchronous and if I want to properly implement the onSavedInstance() with bundle, there would be certain penalties in runtime with async <=> synchronous conversion, and again, the onCreateView() spamming in life cycle.

In addition, I decided to go with fragment because of the coupled UI elements (editor - webview, menu and toolbar), just fyi. And for time being, to retain the state at activity level, you just need to setup and retrieve the fragment with the (support) fragment manager. I would investigate this further to see if there is any good enough approach to properly implement it with saved bundles of onSavedInstance and onCreate()/onCreateView()/onResume()/(...) or coroutines or so

**Comment by daothanhduy305** [comment]
About the fragment -> view suggestion, I have thought of it many times. But it would just happen once I succeed myself in modularizing this whole fragment into 3 independently separated modules (editor/menu/toolbar). This project is still immature and even needs further helps from the other developer to make things faster than I lonely improve it myself. That's why, according to the versioning semantic, it hasn't been able to make itself to v1.0.0 yet 😢.

**Comment by AndroidDeveloperLB** [comment]
"would be triggered multiple times on activity restart" - No. It should occur just once. Never saw it occur multiple times. Unless you have multiple views of the same type, which makes sense, but it's not really needed here...
About webview, this is too bad. Maybe that's why for rich text editing, it's better to use spans.
About fragment, this should be in a sample, not in library. Library should be with parts that can be replaced : toolbar, menu, ... The view is the most important thing. The rest are optional, and should be handled by us. You can provide a default implementation for the toolbar though.

What is the menu? I see just a toolbar and a view to type in.
You mean the top toolbar, and its menu items there? This is also a part of the fragment?

**Comment by daothanhduy305** [comment]
For the fragment things, again, yes, I'm planning to separate things into separated modules. I have told you many times. This is the original design of the original MRichEditor, from which I ported. And I am planning to improve it by separating things into modules but it would take (much) time since I have also other enterprise projects to work on (this is not only my thesis but I'm also using this editor in some of my other business projects).

And this is what I mean for "menu"

![img_20180222_183146](https://user-images.githubusercontent.com/14959405/36536223-be02d47e-17fe-11e8-8a17-74fbe57aa0a3.jpg)

**Comment by AndroidDeveloperLB** [comment]
Seems to be a part of what the toolbar does.
I mean, it already has bold button, italic, and some others...

**Comment by daothanhduy305** [comment]
Yeah, mayb I would try to merge it into toolbar only instead. That's would make things much easier. Thank you for the idea 😉

**Comment by AndroidDeveloperLB** [comment]
As long as it's for controlling the states of the editor view, it falls under the purpose of the toolbar. Doesn't matter how the toolbar looks like (could even be a non-toolbar view).
