### ISSUE TITLE
android10 can't insert image

### ISSUE THREAD

**Issue by Felis-nigripes** [daothanhduy305/KRichEditor#21]
android10 can't insert image

**Comment by daothanhduy305** [comment]
@Felis-nigripes Is this only happening to android 10? As I have tested against the android 11 emulator, I don't have the issue.

If you mean my sample app, it was actually because of the missing [requestLegacyExternalStorage="true"] in the Android Manifest. This should be handled by the app developer instead of me.

Here is the article i found about it: https://trendoceans.com/how-to-fix-exception-open-failed-eacces-permission-denied-on-android/
