### ISSUE TITLE
Bug: text caret doesn't appear on correct place when writing

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [daothanhduy305/KRichEditor#5]
When writing in RTL language, the caret stays on the same place, instead of moving.
See attached video.
[device-2018-02-11-160111.zip](https://github.com/daothanhduy305/KRichEditor/files/1714424/device-2018-02-11-160111.zip)

Such behavior of staying on same place should be for Hebrew only if aligned to the left, just as it occurs for English if aligned to the right.

**Comment by daothanhduy305** [comment]
I see, however it's holiday in my country for over a week so I have not been with my computer to look into it. Can you tell me if it behaves the same with official QuillJs? You can try their editor online at their homepage.

**Comment by AndroidDeveloperLB** [comment]
If I open the web browser with [this link](https://quilljs.com/) (right page sample, with alignment) , I can notice this issue there too. Here's a video:
[device-2018-02-11-174057.zip](https://github.com/daothanhduy305/KRichEditor/files/1714515/device-2018-02-11-174057.zip)


However, I know that in Google Docs it works well.

**Comment by daothanhduy305** [comment]
Thanks. Unfortunately, since we are using QuillJs as base so maybe we'll have to report to them and then wait for the source being patched. For gg docs and gg's other products, they use a framework that is written by them to build their editors (not a ready-to-use editor itself, of course) that I forgot the name. For sure they are more flawless than any other open-source ones ;). Anyway, I will try and see if I can do anything about this after the holiday then :).

**Comment by AndroidDeveloperLB** [comment]
OK here:
https://github.com/quilljs/quill/issues/1954

**Comment by daothanhduy305** [comment]
OK, so I guess I would temporarily close this and #4 until I get further info from QuillJs regarding this issue (already subscribed to your ticket on QuillJS). For now, I would mark this project to be "Not supporting RTL". I hope you understand, thank you 😄.
