### ISSUE TITLE
Question: How to import from HTML?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [daothanhduy305/KRichEditor#8]
It's possible to export to HTML, but how can I get the HTML and import it into the library?

**Comment by daothanhduy305** [comment]
I would prefer to not implement this feature due to possible vulnerability and trouble that it might cause. More info can be found from: https://quilljs.com/docs/modules/clipboard/#dangerouslypastehtml

**Comment by AndroidDeveloperLB** [comment]
I mean save and load the content made by the library.
What's the point of being able to edit text, if I can't save and load it later to be edited again...
And to be able to view it in other places, such as a web browser...

**Comment by daothanhduy305** [comment]
Oh, I see. So, is this what you mean?

> To retrieve HTML code:

    editorFragment.editor.getHtml( ValueCallback {
           do_something_with(it)
    } )
       
> To retrieve text:

    editorFragment.editor.getText( ValueCallback {
            do_something_with(it)
    } )

"it" here is either the html string or content text. Just do whatever you like with "it" (save and load it to somewhere). I interpreted your request as to load a (saved) html snippet into the editor and showed you the potential troubles it might happen.

Anyway, second thought, you're right, I would investigate to try making an approach to load the saved html snippet (override the whole content with saved one, yet not inserting at the middle) into the editor as it's kinda basic.

**Comment by daothanhduy305** [comment]
For time being, please use the getContents() and setContents() method of the internal editor to save/load: 398bc3cc

**Comment by AndroidDeveloperLB** [comment]
I don't understand what you've understood of what I wrote. So I will make it simple:

1. How do I save to HTML from the library, into a file?
2. Given the file we've created, how do I load its content into what you've created?

**Comment by daothanhduy305** [comment]
1.     editorFragment.editor.getHtml( ValueCallback {
           do_something_with(it) // Save the "it" - html string - to file, library or whatever, wherever you like
        } )
2. Not implemented due to possible trouble in link I linked for you (https://quilljs.com/docs/modules/clipboard/#dangerouslypastehtml). Please use the function editorFragment.editor.getContents ( ValueCallback {...} ) exactly like (1) above and then editorFragment.editor.setContents(savedContent) - 398bc3c

About (2), what I tried to say is, at first, instead of making an api allowing html snippet insertion possible everywhere in the content which might cause bugs and vulnerability, I would make it to be like: inserting html snippet would replace the whole current content with the saved snippet.

However, now I rethink it twice and decide not to. Because clearly it's a whole hole to exploit:
> Improper handling of HTML can lead to cross site scripting (XSS) and failure to sanitize properly is both notoriously error-prone and a leading cause of web vulnerabilities.

Another reason to not to implement it is:

> The snippet is interpreted by Clipboard matchers, which may not produce the exactly input HTML.

So basically, if you want to save it and to be able to load it back later, just use the getContents(...) and setContents(...) api like I stated in (2). Document for that api would be updated later as it's WIP for now.

**Comment by AndroidDeveloperLB** [comment]
OK, please put the instructions for these two in the main page of the repo.

**Comment by AndroidDeveloperLB** [comment]
Why close it?
I don't see it in the main page of the repo

**Comment by AndroidDeveloperLB** [comment]
Oh it's here:
https://github.com/daothanhduy305/KRichEditor/wiki/Kotlin-api:-Advance
?
