### ISSUE TITLE
Question: is it possible to customize the look of the toolbar?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [daothanhduy305/KRichEditor#9]
Or maybe I could even create my own toolbar, and call actions on the library by clicking on its buttons?

**Comment by daothanhduy305** [comment]
I would implement a way to disable the toolbar later (but not sure since the toolbar, the menu currently is kinda integrated to the editor themselves). The editor's api can be accessed through (editorFragment).editor.command(params) (can be derived from the KRichEditor class) and would be documented later then :).

**Comment by AndroidDeveloperLB** [comment]
Wait, so it is possible, or not yet?
Or is it possible to some extent ?

**Comment by daothanhduy305** [comment]
@AndroidDeveloperLB it is possible to some extent. Coz if you look at the source code of the toolbar you would have the idea yourself :). But the customizations would be a little bit ugly to do at current state.

**Comment by AndroidDeveloperLB** [comment]
Suppose I wish to change how each button look, or is positioned, or even put some buttons on other places, is it possible? Maybe I could hide the toolbar of the library, and put my own?

I saw that you can call commands, such as this:

> editorFragment.getEditor().command(EditorButton.IMAGE, true (for local path - Base64)/false (for URL), path/URL: String)

Is it possible for the other commands too?

**Comment by daothanhduy305** [comment]
@AndroidDeveloperLB yh, you can re-organize the button positions or even disable ones you don't need. It's included in the instruction also under the toolbar layout customization (make the list to only ones u need and with however positioning you like).

For the command api, yh, u can access the others that way, too. However, pls read the src code for proper params (and the method is kinda ugly to use as stand-alone). I will document/reimplement it afterwards.

**Comment by AndroidDeveloperLB** [comment]
I can even completely hide the toolbar of the library, and use my own, mimicking what it has ?
It's just that the designer will surely want to use different styles for everything ...
We only need to use a very small set of functions for now, though:
-Bold
-Italic
-Underline
-Bullets
-Numbers
-attach photo

We also wanted to add a checklist, but I don't see it here, and in fact in any other library. 

Alignment is also an issue on this library and RTL support especially. But you wrote me that it's because of Quill. Do you think they will fix those issues soon? I have to decide which library to use, and currently I', thinking of this library vs another ([here](https://github.com/1gravity/Android-RTEditor)) . 
The advantage of the other library is that it has better RTL and alignment support, and that it doesn't seem to use WebView, so all is native of Android. It also has some kind of way to customize the UI.
The disadvantage is that it has other things that I can't see that can be customized: photo chooser, camera photo handling. Also the toggles don't work in an intuitive way.

**Comment by daothanhduy305** [comment]
Tbh, it's kinda important bug to me so I think QuillJs devs would look into it, but I'm still impressed at its existence for age like that. About this project, I initially wanted to further develope the MRichEditor project into a plug-able editor library and would respect his implementations at certain degree (that explains why I picked up webview implementation). That's why atm, the ui is kinda tightly relevant between ui parts: webview, toolbar and menu since the original project was designed that way.

I'm also aware how crappy webview approach compares to native one, but well... :pensive:

Anyway, I will try my best to modularize this into a potentially hack-able editor :relaxed: (and fyi, this is my thesis project)

**Comment by AndroidDeveloperLB** [comment]
Oh you do it as a student work?
Nice.

**Comment by AndroidDeveloperLB** [comment]
Why close it?
Is it possible now?
